### ISSUE TITLE
Not able to listen music on other device

### ISSUE THREAD

**Issue by krishnameena** [bryan-y88/Musics_Around#1]
I am able to connect both the devices but music is not playing in the other device.

I am getting this error   

```
2-11 20:04:29.711 26520-32210/com.example.musicsaround D/ClientSocketHandler: Socket connection has ended.
                                                                               java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
                                                                                   at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
                                                                                   at libcore.io.IoBridge.recvfrom(IoBridge.java:556)
                                                                                   at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
                                                                                   at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                                                   at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                                   at java.io.InputStream.read(InputStream.java:162)
                                                                                   at com.example.musicsaround.speaker.ClientSocketHandler.run(ClientSocketHandler.java:69)
                                                                                Caused by: android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
                                                                                   at libcore.io.Posix.recvfromBytes(Native Method)
                                                                                   at libcore.io.Posix.recvfrom(Posix.java:185)
                                                                                   at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
                                                                                   at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
                                                                                   at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485) 
                                                                                   at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37) 
                                                                                   at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237) 
                                                                                   at java.io.InputStream.read(InputStream.java:162) 
                                                                                   at com.example.musicsaround.speaker.ClientSocketHandler.run(ClientSocketHandler.java:69) 
```

**Comment by bryan-y88** [comment]
Hi Krishna, thank you for your interest. However, I no longer support this project as it has been years since the development, and android has gone through many versions, and the devices I tested were first gen of nexus 7's.

Just by glancing over the error message. I'd say start by looking at why the socket connection timed out. Are both devices on the same local area network? Is there a firewall? Are there port usage restrictions? 
Also I would check the code and make sure both devices can connect and send over simple string commands.

--
Best Regards,
Bryan Yan

**Comment by manujvashist** [comment]
One reason can be your phone's don't support NFC which is used in app to share the music.
Bryan can you update this project once again please.

**Comment by bryan-y88** [comment]
It's not NFC, it's Wifi Direct.
https://developer.android.com/guide/topics/connectivity/wifip2p.html

**Comment by krishnameena** [comment]
My phone is supported NFC and WiFi Direct both, should I need to change something in the code?

**Comment by krishnameena** [comment]
any update for me ?

**Comment by manujvashist** [comment]
I have resolved all the errors I'll upload the code soon on github .

**Comment by krishnameena** [comment]
Thank you so much! I am waiting..

**Comment by krishnameena** [comment]
@manujvashist any update for me ?

**Comment by jasmeetsinghlotey** [comment]
i also need working demo of this project, I think it has missing classes.

**Comment by krishnameena** [comment]
Did you get working demo of this project ?

**Comment by manujvashist** [comment]
yes!! see in my repositories.
do star the repo and try to contribute to it.

**Comment by iFruit** [comment]
@manujvashist cannot find any demo from musics_around in your github profile!

**Comment by ranaparamveer** [comment]
@manujvashist You got any working demo of the project?
